version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domiapp-backend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/__pycache__/
      - /app/.venv/
    environment:
      - ENV=dev
      - DEBUG=True
      - LOG_LEVEL=INFO
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn app.api:app --host 0.0.0.0 --port 80 --reload
    networks:
      - domiapp-network

networks:
  domiapp-network:
    driver: bridge 